FROM ubuntu:16.04
MAINTAINER Anderson Miller <anderson.miller@frogdesign.com>

RUN echo "8.8.8.8" >> /etc/resolv.conf
RUN echo "8.8.4.4" >> /etc/resolv.conf
RUN apt-get update
RUN apt-get install -y python3.5-dev python3.5 virtualenv python3-pip libgrpc-dev
RUN pip3 install --upgrade pip
RUN pip3 install grpcio
RUN mkdir /frog
COPY . /frog/
WORKDIR /frog/

CMD ["/usr/bin/python3","robot_server.py"]
EXPOSE 50051

