# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages.proto',
  package='robotics',
  syntax='proto3',
  serialized_pb=_b('\n\x0emessages.proto\x12\x08robotics\"7\n\rFieldPosition\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\x10\n\x08inverted\x18\x03 \x01(\x08\"M\n\x0b\x41rmPosition\x12\x0c\n\x04\x62\x61se\x18\x01 \x01(\x05\x12\x10\n\x08shoulder\x18\x02 \x01(\x05\x12\r\n\x05\x65rror\x18\x03 \x01(\x08\x12\x0f\n\x07message\x18\x04 \x01(\t2Q\n\x0ePositionFinder\x12?\n\x0bGetPosition\x12\x17.robotics.FieldPosition\x1a\x15.robotics.ArmPosition\"\x00\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_FIELDPOSITION = _descriptor.Descriptor(
  name='FieldPosition',
  full_name='robotics.FieldPosition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='robotics.FieldPosition.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='robotics.FieldPosition.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='inverted', full_name='robotics.FieldPosition.inverted', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=83,
)


_ARMPOSITION = _descriptor.Descriptor(
  name='ArmPosition',
  full_name='robotics.ArmPosition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='base', full_name='robotics.ArmPosition.base', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='shoulder', full_name='robotics.ArmPosition.shoulder', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error', full_name='robotics.ArmPosition.error', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message', full_name='robotics.ArmPosition.message', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=162,
)

DESCRIPTOR.message_types_by_name['FieldPosition'] = _FIELDPOSITION
DESCRIPTOR.message_types_by_name['ArmPosition'] = _ARMPOSITION

FieldPosition = _reflection.GeneratedProtocolMessageType('FieldPosition', (_message.Message,), dict(
  DESCRIPTOR = _FIELDPOSITION,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:robotics.FieldPosition)
  ))
_sym_db.RegisterMessage(FieldPosition)

ArmPosition = _reflection.GeneratedProtocolMessageType('ArmPosition', (_message.Message,), dict(
  DESCRIPTOR = _ARMPOSITION,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:robotics.ArmPosition)
  ))
_sym_db.RegisterMessage(ArmPosition)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces


  class PositionFinderStub(object):

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.GetPosition = channel.unary_unary(
          '/robotics.PositionFinder/GetPosition',
          request_serializer=FieldPosition.SerializeToString,
          response_deserializer=ArmPosition.FromString,
          )


  class PositionFinderServicer(object):

    def GetPosition(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_PositionFinderServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'GetPosition': grpc.unary_unary_rpc_method_handler(
            servicer.GetPosition,
            request_deserializer=FieldPosition.FromString,
            response_serializer=ArmPosition.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'robotics.PositionFinder', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaPositionFinderServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def GetPosition(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaPositionFinderStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def GetPosition(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    GetPosition.future = None


  def beta_create_PositionFinder_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('robotics.PositionFinder', 'GetPosition'): FieldPosition.FromString,
    }
    response_serializers = {
      ('robotics.PositionFinder', 'GetPosition'): ArmPosition.SerializeToString,
    }
    method_implementations = {
      ('robotics.PositionFinder', 'GetPosition'): face_utilities.unary_unary_inline(servicer.GetPosition),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_PositionFinder_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('robotics.PositionFinder', 'GetPosition'): FieldPosition.SerializeToString,
    }
    response_deserializers = {
      ('robotics.PositionFinder', 'GetPosition'): ArmPosition.FromString,
    }
    cardinalities = {
      'GetPosition': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'robotics.PositionFinder', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
